---
title: "june"
format: html
---

*work in progress*

*You probably think that your mom's meatballs are the best meatballs, just like I think my mom's meatballs are the best ones, but it could be that neither one makes the best meatballs*

If I am considered to be the best in someone's eyes, but someone else thinks that another person is the best, am I truly the best? Are we all someone's best/favorite only to realize that it means that none of us are the best.

My mother is feeling ill---she has been sick her whole life, a sickness that exhausts the body. It's genetic---this disease...but that is not what we are here for. The hospital lights are always blinding, the shuffling of staff and patients, the dull hum of the central unit---the ache building in my shoulders---I always carry my stress there.

My head hurts again, I've been here for over 9 hours. the stress will kill me, I've started to become numb again from the pain...I've become a sort of hospital ghost--floating around the hallways, standing still at times--the rain continued outside.

```         
it will pass    eventually
```

*eats away this heart of mine*

i keep thinking about this lyric and for some reason it sits on the tip of my tongue.
