---
title: "May Flowers"
format: html
author: "Marlin Alejandro"
---

*Here are the may flowers, and there are plenty on campus.*

The days are approaching, the memories fleeting, like the cherry blossoms on campus. My college life seems to be slipping from my fingers and with it the end of my teenage years and the beginning of my 20s.

I often feel as if I missed out on milestones that people my age are expected to reach, but then again, I am not everyone, am I?

In my Ecopoetics class, we are required to have a journal: nature journal. Meant for our thoughts as we contemplate and consider our relationship with nature and where we stand. I have taken a liking to going on walks around campus after class. The best thing about this spring semester is the lack of restraints on my schedule. I have actually not written much in my journal, not from lack of thinking, but rather because I tend to carry my own personal journal.

I convinced my sister to carry her own nature journal, so that she can write observations, thoughts, etc. I am a firm believer that everyone is born a poet, we all have something to say, don't we? I spent hours sitting between the trees, laying on them as I looked up---the small beams of sun peaking through (when writing this, I kept typing "sin" instead of "sun", how intriguing). 


I feel oddly miserable. Guilt eats at me, and I cry every night. I am close to graduation but one of my friends has passed away. I lay on my bed and I think about how she would have made a wonderful teacher. She loved kids, and she lived nearby. We only had one class together but, out of everyone in that class, she was my favorite. We talked about our experiences growing up in New York. She was the first person who immediately knew where I lived the moment I said the name, and it's no wonder, she lived the next train stop away. There is only one big mall nearby and we laughed about the fact that we loved the same shops. I had gone home and I cried, because I can at least go back home. I can go to our mall, and I can visit the stores, and eat all the greasy food, and I can take the subway to her stop, and I can graduate. A few years back, I wanted to die. I had to go to the hospital for it---had to visit a child psychiatrist, and now it feels as if it should have been me instead of her. I made it to 21, and I'll make it to graduation, but she never will reach 22, and she won't walk on stage. How bitter. 


Writing about her has helped, and talking---I've never been good at talking about my feelings out loud, my voice always gets caught in my throat, my body tenses, and I would rather have the Earth swallow me whole. They made a memorial for her in Pendelton East. Flowers, candles, conchas. It was beautiful. I saw my philosophy professor, and wondered how she must feel---how do professors feel when they lose a student. We greeted each other, and we stood in silence. Words did not have to be shared for us to know what we wanted to say. I hope my professor enjoyed the show. 


I have a confession---I've been isolating myself. I need time to regulate my emotions, time that I prefer having alone. People keep asking where I have been, and I can't say, "Oh, I've been having an overflow of emotions, where I feel as if I don't deserve to be here, but then I am so happy that I am alive, and that I can experience all life has to offer", saying that is daunting enough on its own. Plus, I know that if I were to say that, people will worry. But they'll worry about all the wrong things. I don't need help, I just need to time to sort my feelings. 


I feel better, I no longer cry at night over what could have been and what isn't. I have been slightly irritable though. I don't appreciate when people assume what I am feeling towards them or situations. If I am upset, you'll know I am upset, and I won't lie about it. But people push themselves away, giving me space, because they assume I am angry. I don't know how many times I have to emphasize that I'm not bothered. I'm sorry you feel guilt, but if I, the person who should be upset isn't, then why are you still caught up on it. It's like my mom says "Te estas ahogando en un vaso de agua", you're drowning in a cup of water, seeing problems where there aren't any, and over complicating things. It only makes the situation awkward. I just want this to end. 


I almost forgot to mention that my favorite tree was cut down---rotting on the inside. It was hollow and it was a relfection of what I felt looking down at it. 


### Graduation

Graduation came and there was nothing much to say. I wanted to somehow leave a part of me at Wellesley College, so that she would remember me and to prove that I was there. How to leave behind my print?

The graduation passed by quickly-- I was sitting one moment for rehearsal and then I was walking on stage, waving at a sea of people whose faces I could not see. I graduated, did you see?

妹妹,这仍在进行中


