---
title: "red moleskin"
format: html
author: "Marlin Alejandro"
---

A voice that rings out 

My aunt singing while sewing

Her little escape

- My aunt at 2 a.m.

------------------------------------------------------------------------

\

I wish to go back to the days

Where my cousins and I 

Would sing and play, 

Soaking the sun. 

\

When abuelita would call us

To eat hot soup on an even hotter day.

When we would climb mi abuelito’s red car

And pretend we were driving 

\

Summers that we would spend together

Vividily engraved in my mind

And yet those times spent are all

Now memories, times that will not return,

\

People we will never see, 

Voices we will never harem

And moments that we enjoyed as naive and innocent children.

When I feel far from home,

I close my eyes and pretend

Being seven in Ecuador. 

\

------------------------------------------------------------------------

**\*unedited version\***

A narrative: something about you, something personal, and yet as I pick up my pen, I can’t write anything about myself. I fear that the damage is rooted deep, the generational trauma still there, and the inability to express my emotions is one scar I have not been able to heal. 

- I’m sorry that I failed that class

------------------------------------------------------------------------

\

Jugo de Coco

\

On a hot summer day

My mom would always buy me jugo de coco

It was my favorite drink as a kid

The cart vendor knew to pass by our 

Street, and everyday without miss

A 50 cent drink would be in my hands

As i got older we frequented Ecuador less

Loved ones were lost, crime too high.

It no longer felt like the home I knew when i was 9

\

And yet last year at 16, i went and 

My aunt called me down and passed me a dollar

She had signaled the vendor to come and with a smile told me to run

Running outside brought me to when i was 9 and for a minute, my barrio looked familiar. 

------------------------------------------------------------------------

\

Flour Hands

\

In my childhood I loved

To bake

I would help my grandma when she would

Make desserts

“Con delicadeza, mija” she would tell me

The batter has to be mixed consistently 

Changing rhythm would not allow it to rise

I would nod and not let anyone else mix,

After all too many different hands will

Ruin it

Only now as a college student do I realize

My abuelita
