---
title: "thought daughter"
format: html
author: "Marlin Alejandro"
---

##     **Fragments of Thoughts that Once Were**

\

**Feb 1, 2026**

\

Walked with a friend to buy groceries, we both stood under the beams of the moon. I mentioned my favorite story, one that my father used to tell me:

 A man who tended his land all day,

Never resting, never resting, always busy —

The Moon approached him one night, begged him to go home,

But there can be no home without labour. 

As punishment, for ignoring her pleas,

 	 he was made to tend his land eternally, 

His wife and child, figments of the past.

\

 She lent me her ear, eyes searching for the farmer and his ox. Is he still tending to his land? I shrugged, my fingers numb from the cold, I like to think the Moon granted him peace eventually, she is after all a guardian. We stood in silence, no movement from either of us; Our breaths were almost still that we could have passed as ghosts. I smiled brightly at her, holding out my hand. It's cold, let’s go inside. We ran toward the dim light of the store, laughing, our forms flickering like two stars in the sky.

“I see the moon, and the moon sees somebody I want to see”

------------------------------------------------------------------------

**Feb 1, 2026**

\

Shadows are essentially a proof of existence.  Even while not looking directly at the tree, its shadow must mean that it exists; it moves, as if it were its own separate entity. It would be interesting to think of when there are no shadows. When light hits an object or a living being in a certain way, no shadow is produced. Would it really exist? If we could not see it, and there was no shadow, can we say something is real? 

------------------------------------------------------------------------

**Feb 4, 2026**

\

I sit beside my friend, 

rays of sun bouncing against the wooden table. 

Miniscule dust particles shimmering under the light, 

peelings of a clementine —

Home.

bowls of peeled and cut fruit,

 Distant chatter coming from the kitchen:

My mother’s voice —

 I am cold.

 I’ll call my mom later

------------------------------------------------------------------------

**Feb 7, 2026**

\

Snow,

Snow in spring,

Shoes all wet,

Shoes dripping, 

Wet,

Wet,

Cold,

Cold,

I will make tea —

\

forgetting to check the forecast

------------------------------------------------------------------------

**Feb 11, 2026**

\

The snow slushed

 under my shoes,

Is spring coming soon? 

I look at my watch, 

Tick   Tick     Tick

running late—

Fear of slipping.

Fear of loss

\

Shadow of a lamp,

Black on a pristine white canvas, 

Glistening under the sun,

 I want to lie upon it,

 The snow will cushion me. 

I stop.

I stare.

How time flies, 

I’ll leave tomorrow.

\

------------------------------------------------------------------------

**Feb 15, 2026**

\

Hop —

   —  Hop —-

—Hop —-     Hop—-

\

I wonder where the rabbits go in this cold

She looks at me

And I at her,

Two creatures under the same sky.

 I hope she makes it home safe, 

guided by the dim lights of the lamps, 

the moon hidden. 

\

------------------------------------------------------------------------

**Feb 18, 2026**

\

I walk across campus,

Stepping –  stepping — 

Fluffy white, crushed under my shoes. 

Mary Janes. 

The front of my shoes, scuffed —

How many years? 

Only yesterday my older sister gifted me these shoes. 

Her first paycheck,

 I lift my foot,

a mark remains. 

It will be erased.

------------------------------------------------------------------------

**Feb 21, 2026**

\

Waking up at 4 a.m.

\

The lamposts illuminate the walkpath, 

dark looming pines leaning, 

telling each other secrets. 

The snow weighing heavy on their limbs, 

I stand under such trees,

 Wonder,

 if I too can hear their secrets

 if I stay still for long enough,

 A minute passes,

 or maybe seconds.

 I continue my trek,

 maybe when I am not in a rush,

 I will have the time to listen. 

\

------------------------------------------------------------------------

\

**March 7, 2026**

\

My tulips bloomed, 

Maybe spring is coming afterall. 

The drip-drop of the snow melting at my window. 

It feels weird seeing my tulips bloom,

after everything that happened. 

\

My tulips white. 

My tulips white as the snow outside. 

White tulips stand for innocence, 

Forgiveness,

new beginnings. 

How strange,

My tulips decided to bloom today. 

\

“Sad news regarding a member of our campus community” - 7:35 p.m.

\
\

------------------------------------------------------------------------

\

**March 16, 2026**

\

milky white fog

 hides the tall buildings, 

raindrops on the branches, 

chirping of birds, 

hands are in my pockets, 

i let out a breath, 

watching the fog move,

move like a stream, 

Like soft waves —

Humming,

Hum, 

I wait

\

------------------------------------------------------------------------

\

**March 30, 2026**

\

The trees are still bare —

Small fiery leaves still clinging on,

To a spring that is around the corner, 

But these leaves,

These leaves will not last.

\

New buds are coming in,

Speckles of green ready to bloom,

And those forgotten leaves,

Valiant leaves that held throughout winter,

They will fall, for spring to come

\

------------------------------------------------------------------------

\

**Mar 30, 2026**

**Lines Written on a Rainy Walk**

\

A forgotten roll lays on the ground,

Maybe someone was hungry, 

And that hunger must have fled

And taken flight

Because now the roll is covered in soil,

The rain, dusting it over.

\

I am not the only one

Who passes by the roll,

Eyes glazing over, lips pursed,

Littering—

I however, feel as the roll

\

Feel the people passing by me, 

Watching, observing, but never stopping

Remaining untouched,

I am untouched,

Untouched –

\

In the end

The birds and the embrace of a mother

Will cradle my broken begotten body,

Will love only come at death?

Does one have to die,

To feel the warmth?

------------------------------------------------------------------------

**To a Friend**,

\

It’s almost the end of the semester. Today, the weather is beautiful, the birds are singing again, and the daffodil bulbs look about ready to bloom. I hope that you can feel the beginning of spring, wherever you are now. I went back home…the same place we both called home — did you think of home? Of the warmth that comes when stepping foot in a city that has seen you grow — I went to the mall, the one that we both talked about going during high school, teenagers were everywhere, a reminder of what we once were. The spot that we both call “ our favorite”, still stands. I look away. My throat dry, a huge lump of possibilities being pushed down, hand clenching shirt, clawing at my heart, tear it out, tearing it out.

Eyes burning, heat flaring behind my skull, get out, leave now.

I wish you could have gone back home, you should have been here, standing where I am.

I’m sorry — I hope you found peace. 

\

------------------------------------------------------------------------

\

**April 3, 2026**

\

One turtle,

Two turtles,

Three turtles,

Heads raised up,

Beams of sun

Reflecting on their shells —

I miss home.

------------------------------------------------------------------------

**April 3, 2026**

\

One geese, 

Two geese, 

Lying on the vibrant green.

Long necks curled in, 

Enjoying the summer breeze.

\

------------------------------------------------------------------------

**April 3, 2026**

\

“The bright song of the Tufted Titmouse is one of the first sounds of spring across Eastern North America.”

\

Warmth dances across my face

Wind blowing gently,

Kissing my nape,

The song of the titmouse

Surrounding me,

I could almost grow wings

And take flight

------------------------------------------------------------------------

**April 6, 2026**

\

In ancient times, it was believed that flowers were red from the spilled blood of innocents. I wonder how it came to be, that red flowers are gifted for deep love. When the crimson would go deep into mother earth, tainting the once white flowers, did we decide then, that the only way to penance is to take the sacrifice of the innocent and take this bloodied flower as an act of devotion, a symbol of love rather than loss.

\

------------------------------------------------------------------------

**April 6, 2026**

\

Humanity shifted the moment we decided to hunt whales. 

Whales, who are one of our eldest ancestors, whose eyes have knowledge 

that we can only dream of learning. 

Whose songs, up close, pull deep, deep inside you,

Who stay with their dead calfs, pushing them for days,

 Mourning —

 When the last Dodo was killed for being kind, 

we doomed our planet. 

When the last Stellar’s cow whose only fault was her own curiosity, 

approaching nearby boats, then,

we must have cursed our future generations. 

When sharks were finned for sport, their hearts hanging outside their jaws, 

fear and desperation the last emotion they felt. 

Their corpse on display —

When the great lonesome tortoise, George, 

who saw the beginning of civilization, had died, we died with him.

When pigeons were taken as instruments in war; 

messengers that took flight, awarded for heroics, 

only to be called pests, did we fail then?

Did we fail when we sent a stray into space, 

no return flight —

Did we advance as a society or did we fail one another? 

Did our mother,    the earth,    weep when she heard,

“We will drill, baby, drill”; 

when her children d e p a r t e d this world, when her lands were burned. 

We go to the stars above, searching for life, searching for meaning, 

While the ground beneath our feet dries up, water acidic,

organisms that have existed since the time of creation, 

now only 1,000, 

                    now only 100, 

                                        now only 10, 

                                                      soon none.

\

When the whales were hunted, did they cry, 

tears filling up the seas, 

their calves purposely used as bait. 

Did they decide to stay alongside their only child, 

knowing, 

knowing,

knowing 

that their end would come. 

\

We are at a time where it matters where you stand - Robin Wall Kimmerer

------------------------------------------------------------------------
